import Head from "./head";
import Footer from '@/components/footer/Footer';
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Strike Sheet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    <>
      <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
        <Head />
        <body suppressHydrationWarning>{children}</body>
      </html>
      <Footer />
    </>
  );
}
