import Head from "./head";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Strike Sheet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <Head />
      <body>{children}</body>
    </html>
  );
}
